#!/bin/bash

default_user=asinbow.wang
default_pwd=asinbow.wang
default_database=asinbow

if [[ $# = 0 ]]; then
    host="localhost"
    user=$default_user
    psw=$default_pwd
else
    if [[ $1 == *@* ]]; then
        args=$1
        args=(${args//@/ })
        user=${args[0]}
        host=${args[1]}
        echo $user
        echo $host
    else
        user=$default_user
        host=$1
    fi

    if [[ $# = 2 ]]; then
        psw=$2
    else
        if [[ $user = $default_user ]]; then
            psw=$default_pwd
        elif [[ $user = "root" ]]; then
            psw="shuobaotang"
        fi
    fi
fi

if [[ $host =~ ^[0-9]+$ ]]; then
    host="192.168.0."$host
else
    host=$host
fi

cmd="mysql -h$host -u$user -p$psw $default_database"
echo $cmd
mysql -h$host -u$user -p$psw $default_database

